name: aws_log_csv

on:
  schedule:
    - cron: '15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python Script
      run: python aws_csv.py
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Commit and push changes
      run: |
        git config user.email "wls5258@naver.com"
        git config user.name "202116302"
    
        git add ./output/*.csv
        git clean -xdf
        git commit -m "Update Data - $(TZ='Asia/Seoul' date +'%Y-%m-%d %H:%M')"
        git push 
